name: GameCI

on:
  push: {}
  pull_request_target: {}
  workflow_dispatch: {}

jobs:
  release:
    needs: test
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    permissions:
      contents: write
    uses: Narazaka/vpm-repos/.github/workflows/release.yml@main
    with:
      exclude: |
        Tests
        Tests.meta

  test:
    uses: Narazaka/vpm-repos/.github/workflows/gameci.yml@main
    permissions:
      checks: write
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    with:
      unity: ${{ matrix.unity }}
      vrcsdk-type: avatars
      vrcsdk-version: ${{ matrix.vrcsdk-version }}
      repos: |
        https://vpm.nadena.dev/vpm.json
        https://vpm.narazaka.net/index.json
      packages: |
        nadena.dev.ndmf ${{ matrix.ndmf }}
      name: NDMF=${{ matrix.ndmf }}
      assemblyNames: net.narazaka.vrchat.jnto.Tests.Editor
      assemblyFilters: +net.narazaka.vrchat.jnto.*,-net.narazaka.vrchat.jnto.Tests.Editor
    strategy:
      fail-fast: false
      matrix:
        include:
          - unity: 2022.3.22f1
            ndmf: 1.11.0
            vrcsdk-version: 3.7.4
